# Generated by Django 6.0.6 on 2026-06-29 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super admin'), ('receptionist', 'Receptionist'), ('doctor', 'Doctor'), ('laboratory', 'Laboratory'), ('pharmacist', 'Pharmacist'), ('midwife', 'Midwife'), ('vaccinator', 'Vaccinator'), ('malnutrition', 'Malnutrition')], max_length=32)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('allowed_permissions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__first_name', 'user__last_name', 'user__username'),
            },
        ),
    ]
