# Generated by Django 6.0.6 on 2026-06-30 16:02

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_website_content_editor_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('position', models.CharField(max_length=120)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('join_date', models.DateField()),
                ('national_id_card_number', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_info', models.TextField(blank=True)),
                ('mobile_number', models.CharField(blank=True, max_length=32)),
                ('image', models.FileField(blank=True, upload_to=accounts.models.employee_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('first_name', 'last_name', 'id'),
            },
        ),
    ]
