# Generated by Codex for laboratory billing workflow.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_labtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldocument',
            name='payment',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='clinical_document',
                to='clinic.payment',
            ),
        ),
    ]
