EXPENSE_CATEGORIES = [
    'Car fuel',
    'Misc (motafariqa)',
    'fixings',
    'educational classes expenses',
    'Fuels (mahroqat)',
    'tax',
    'safayi',
    'washing materials',
    'Garbage transfer',
    'salary',
    'transport',
    'advertiments',
    'stationery',
    'laboratory equipments',
    'equipments',
    'electricity',
    'internet',
    'mobile credit',
    'building rent',
    'water',
    'Subsistence(eaasha)',
    'supplies (azoqa)',
]
