EXPENSE_CATEGORIES = [
    'Office rent',
    'Clinic building rent',
    'Warehouse rent',
    'Staff housing rent',
    'Electricity bill',
    'Generator diesel',
    'Generator petrol',
    'Solar system maintenance',
    'Battery replacement',
    'Water supply',
    'Water tank cleaning',
    'Internet service',
    'Telephone recharge',
    'Mobile data packages',
    'Printer paper',
    'Printer toner',
    'Photocopying',
    'Stationery',
    'File folders',
    'Registers and logbooks',
    'Receipt books',
    'ID cards and badges',
    'Office furniture',
    'Office equipment repair',
    'Computer purchase',
    'Laptop repair',
    'Software subscription',
    'IT support',
    'Network equipment',
    'CCTV maintenance',
    'Security guard salary',
    'Cleaner salary',
    'Driver salary',
    'Receptionist salary',
    'Doctor salary',
    'Gynecologist salary',
    'Midwife salary',
    'Nurse salary',
    'Laboratory technician salary',
    'Pharmacist salary',
    'Vaccinator salary',
    'Malnutrition staff salary',
    'Ultrasound technician salary',
    'Data entry salary',
    'Accountant salary',
    'HR staff salary',
    'Admin officer salary',
    'Overtime payment',
    'Daily labor wages',
    'Staff per diem',
    'Staff meal support',
    'Tea and refreshments',
    'Guest hospitality',
    'Travel allowance',
    'Vehicle fuel',
    'Vehicle maintenance',
    'Vehicle tires',
    'Vehicle spare parts',
    'Vehicle insurance',
    'Motorbike fuel',
    'Motorbike maintenance',
    'Patient referral transport',
    'Ambulance fuel',
    'Ambulance maintenance',
    'Cold chain maintenance',
    'Vaccine carrier repair',
    'Ice pack replacement',
    'Medical waste disposal',
    'Sharps boxes',
    'Cleaning supplies',
    'Hand sanitizer',
    'Soap and detergents',
    'Disinfectant',
    'PPE supplies',
    'Masks and gloves',
    'Bedsheets and linen',
    'Laundry expense',
    'Toilet supplies',
    'Minor construction',
    'Building maintenance',
    'Plumbing repair',
    'Electrical repair',
    'Painting and renovation',
    'Heating fuel',
    'Fire extinguisher service',
    'Signboard and branding',
    'Community awareness materials',
    'Health education printing',
    'Training materials',
    'Workshop hall rental',
    'Staff training cost',
    'Monitoring visit cost',
    'Supervision travel',
    'Coordination meeting expense',
    'Audit fee',
    'Bank charges',
    'Money transfer fee',
    'Legal documentation fee',
    'Licensing and permits',
    'Tax and government fee',
    'Postage and courier',
    'Customs clearance',
    'Procurement transport',
    'Loading and unloading',
    'Laboratory reagents',
    'Laboratory consumables',
    'Sample collection supplies',
    'Microscope maintenance',
    'Centrifuge repair',
    'Ultrasound gel',
    'Ultrasound probe cover',
    'Pharmacy shelves',
    'Medicine cartons',
    'Cold storage repair',
    'Family planning commodities support',
    'Malnutrition supplies',
    'RUTF handling supplies',
    'Vaccination supplies',
    'Delivery room supplies',
    'ANC clinic supplies',
    'PNC clinic supplies',
    'Dressing materials',
    'Sutures and procedure packs',
    'Emergency medicine top-up',
    'Oxygen cylinder refill',
    'Nebulizer maintenance',
    'Medical equipment calibration',
    'Generator oil',
    'Generator service',
    'Solar technician fee',
    'Snow removal',
    'Flood damage repair',
    'Gardening and compound cleaning',
    'Guesthouse accommodation',
    'Staff accommodation utilities',
    'Translation and interpretation',
    'Community mobilizer stipend',
    'Volunteer support',
    'Donor visibility materials',
    'Documentation and photography',
    'Internet modem replacement',
    'Server and hosting expense',
    'Backup storage devices',
    'Miscellaneous clinic expense',
]
