# Generated by Codex for pharmacy sales workflow updates.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0005_labtest"),
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="customer_type",
            field=models.CharField(
                choices=[("internal", "Internal"), ("external", "External")],
                default="external",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pharmacy_sales",
                to="clinic.patient",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pharmacy_sale",
                to="clinic.payment",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="prescription_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pharmacy_sales",
                to="clinic.clinicaldocument",
            ),
        ),
    ]
