# Generated by Codex for malnutrition stock fields.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0002_sale_customer_type_sale_patient_sale_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="country_of_product",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="medicine",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medicine",
            name="production_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
